server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # CRUCIAL: Esto redirige todas las peticiones a index.html para que React Router maneje las rutas del Frontend sin dar error 404
        try_files $uri $uri/ /index.html;
    }

    # Caché optimizada para archivos estáticos (imágenes, fuentes, JS compilado)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}